### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by michael-duke** [Alusp/World-Health-Assembly#8]
## Feedback on Allusine 
 - Use the colors #272A31, #EC5242, #D3D3D3. Please try to change the 'blues', to match the colors from the template.
 -  Your footer should have the logo aligned to the left and the text to the right both on desktop and mobile versions as it is in the template.
 - Your mobile menu button is not working properly on your About page. Please, check what's happening and fix this issue.

**Comment by Alusp** [comment]
Thanks very much, for the review @Team, Its done.
